In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
import nibabel as nib

### Read 3D Data

In [2]:
data_path = "./../../../Datasets/MICCAI-Challenge-STSR2025-Task1/"
train_labeled_path = data_path + "Train-Labeled/"
train_unlabeled_path = data_path + "Train-Unlabeled/"
val_path = data_path + "Validation/"

In [3]:
img_path = train_labeled_path + "Images/"
mask_path = train_labeled_path + "Masks/"

In [4]:
os.listdir(img_path)

['STS25_Train_Labeled_0002.nii.gz',
 'STS25_Train_Labeled_0021.nii.gz',
 'STS25_Train_Labeled_0030.nii.gz',
 'STS25_Train_Labeled_0017.nii.gz',
 'STS25_Train_Labeled_0011.nii.gz',
 'STS25_Train_Labeled_0007.nii.gz',
 'STS25_Train_Labeled_0019.nii.gz',
 'STS25_Train_Labeled_0018.nii.gz',
 'STS25_Train_Labeled_0022.nii.gz',
 'STS25_Train_Labeled_0024.nii.gz',
 'STS25_Train_Labeled_0004.nii.gz',
 'STS25_Train_Labeled_0025.nii.gz',
 'STS25_Train_Labeled_0003.nii.gz',
 'STS25_Train_Labeled_0001.nii.gz',
 'STS25_Train_Labeled_0023.nii.gz',
 'STS25_Train_Labeled_0008.nii.gz',
 'STS25_Train_Labeled_0005.nii.gz',
 'STS25_Train_Labeled_0009.nii.gz',
 'STS25_Train_Labeled_0012.nii.gz',
 'STS25_Train_Labeled_0016.nii.gz',
 'STS25_Train_Labeled_0006.nii.gz',
 'STS25_Train_Labeled_0013.nii.gz',
 'STS25_Train_Labeled_0014.nii.gz',
 'STS25_Train_Labeled_0028.nii.gz',
 'STS25_Train_Labeled_0010.nii.gz',
 'STS25_Train_Labeled_0015.nii.gz',
 'STS25_Train_Labeled_0029.nii.gz',
 'STS25_Train_Labeled_0027.n

In [ ]:
ids = ["01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"]

for id in ids:

    img1_path = img_path + f"STS25_Train_Labeled_00{id}.nii.gz"
    print("------------------")
    print(f"Checking image {id}:")
    # Read 3D image STS25_Train_Labeled_0005.nii.gz
    img1_nii = nib.load(img1_path)
    img1_data = img1_nii.get_fdata()

    slice = (img1_data.shape[2] // 2) + 50
    # print(slice)

    print( img1_data.shape, img1_data.dtype)


    # Show a middle slice along the z-axis
    # plt.imshow(img1_data[:, :, slice], cmap='gray')
    # plt.axis('off')
    # plt.show()

    mask1_path = mask_path + f"STS25_Train_Labeled_00{id}_Masks.nii.gz"

    mask1_nii = nib.load(mask1_path)
    mask1_data = mask1_nii.get_fdata()
    print( mask1_data.shape, mask1_data.dtype)
    
    print(np.unique(img1_data))
    print(np.unique(mask1_data))

    # Show a middle slice along the z-axis
    # plt.imshow(mask1_data[:, :, slice], cmap='gray')
    # plt.axis('off')
    # plt.show()

<class 'numpy.ndarray'> (266, 266, 200) float64
<class 'numpy.ndarray'> (266, 266, 200) float64
----------------
[-1000.  -999.  -998. ...  3080.  3083.  3095.]
[0. 1. 2. 4. 5. 7. 8. 9.]
<class 'numpy.ndarray'> (266, 266, 200) float64
<class 'numpy.ndarray'> (266, 266, 200) float64
----------------
[-1000.  -999.  -998. ...  3093.  3094.  3095.]
[ 0.  1.  2.  4.  7.  9. 12.]
<class 'numpy.ndarray'> (266, 266, 200) float64
<class 'numpy.ndarray'> (266, 266, 200) float64
----------------
[-1000.  -999.  -998. ...  3093.  3094.  3095.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'> (640, 640, 448) float64
<class 'numpy.ndarray'> (640, 640, 448) float64
----------------
[-1000.  -999.  -998. ...  6555.  6563.  6683.]
[ 0.  1.  2.  4.  5.  6.  7.  8.  9. 12.]
<class 'numpy.ndarray'> (536, 536, 440) float64
<class 'numpy.ndarray'> (536, 536, 440) float64
----------------
[-1000.  -999.  -998. ...  4058.  4069.  4074.]
[0. 1. 2. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'> (536, 536, 440)

KeyboardInterrupt: 

In [ ]:
# print unique values of mask1_data


[-1000.  -999.  -998. ...  3080.  3083.  3095.]
[0. 1. 2. 4. 5. 7. 8. 9.]
